#!/bin/bash
# Downloads posts from a user on Eka's Portal (g4)

# Optional cookie
cookie="$HOME/Downloads/cookies-aryion-com.txt"

help() {
    echo "Usage: ${0##*/} [mode] [user/posts]
Download posts from Eka's Portal (g4)

Arguments:
  -f    (F)ull artist
  -p    Individual (P)osts"
    exit
}

download() {
    # Get header for processing
    head=$(curl --silent --cookie "$cookie" --head "https://aryion.com/g4/data.php?id=$1")

    # Download with wget because it has pretty output
    wget --load-cookies "$cookie" --content-disposition --quiet --show-progress --no-clobber "https://aryion.com/g4/data.php?id=$1"

    # Fix malformed datestamp + get filename (grep string inside quotes and delete \015)
    touch -d "$(
        grep last-modified <<<"$head" |
            sed 's/^last-modified: //g' |
            tr -d : |
            sed 's/./&:/19;s/./&:/22' |
            tr -d '\015'
    )" "$(
        grep filename <<<"$head" |
            grep -oP '"\K[^"\047]+(?=["\047])' |
            tr -d '\015'
    )"
}

# Options via arguments
while getopts fph options; do
    case $options in
    f) mode=full ;;
    p) mode=post ;;
    *) help ;;
    esac
done

# Display help if no mode is set
[ $# -eq 0 ] && help

# Check what mode has been selected
if [ "$mode" = post ]; then
    for postid in "${@:2}"; do
        download "$postid"
    done
    exit
elif [ "$mode" = full ]; then
    # Get amount of pages
    echo 'Checking amount of pages...'
    pages="$(
        curl -s "https://aryion.com/g4/latest/$1" |
            grep -m 1 -o "Page 1 of [[:digit:]]*" |
            awk 'NF>1{print $NF}'
    )"

    echo "Found $pages pages, gathering"
    # Get all pages found
    curl -s "https://aryion.com/g4/latest/$1&p=[1-$pages]" |
        wget --quiet -O-

    # Get only the submissions
    grep view/ |

        # Get only what's inside of each href
        sed -n 's/.*href="\([^"]*\).*/\1/p' |

        # Get rid of everything before last slash, leaving only IDs
        grep -o '[^/]*$' |
        while read -r postid; do
            download "$postid"
        done
else
    help
fi
